### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by deborah-chasman** [Helena-todd/TInGa#2] opened 2020-08-14 21:05 UTC
Hello! I saw your talk at ISMB and am looking forward to trying out TinGa. 

I'm having some trouble with installation of the R package. I'm using R 4.0.2.

1. The DESCRIPTION file says it requires the "qsub" package, which in turn requires libssh. I don't have root access to my server, so I can't install libssh. It looks like qsub is not ever actually used in your code, so I think I should be able to just remove this dependency from the DESCRIPTION file. Will TinGa work without it?

2. read_trajectory_svg.R uses the "workspace" package, which I can't find anywhere on CRAN or Bioconductor. Is it necessary? I ended up moving read_trajectory_svg.R out of the R directory and rerunning document() and install() to successfully install the TinGa package. Will TinGa work as expected without this function?

Thanks!

**Comment by rcannood** [comment] 2020-09-21 11:47
Hello Deborah! 

Indeed, you can remove the qsub and workspace packages from the DESCRIPTION. I have forked this repository and created a pull request. Once merged, your issues should be solved :) 

Kind regards,
Robrecht

**Comment by aoumess** [comment] 2020-10-10 20:49
Hello !
Same problem here with the non-existing "workspace" package... Any news ?
Tried installing on R 3.6.3.

Regards,

Bastien

**Comment by rcannood** [comment] 2020-10-12 09:19
Hello Bastien,

This should not be an issue anymore; the latest version of Tinga does not use workspace anymore. Are you using the latest version of the master branch?

Kind regards,
Robrecht

**Comment by aoumess** [comment] 2020-10-12 09:25
Hi !

Using the default `devtools::install_github()` (I assume this is master by default ?) I still have it :

```
> devtools::install_github("Helena-todd/TInGa/package")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo Helena-todd/TInGa@HEAD
✓  checking for file ‘/tmp/RtmpjRqe6q/remotes293246dbe39/Helena-todd-TInGa-7359c78/package/DESCRIPTION’ ...
─  preparing ‘TInGa’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘TInGa_0.0.0.9000.tar.gz’
   
Installing package into ‘/home/job/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘TInGa’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘workspace’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Exécution arrêtée
ERROR: lazy loading failed for package ‘TInGa’
* removing ‘/home/job/R/x86_64-pc-linux-gnu-library/3.6/TInGa’
Erreur : Failed to install 'TInGa' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/RtmpjRqe6q/file293266ac6327/TInGa_0.0.0.9000.tar.gz’ had non-zero exit status
```

Regards,

**Comment by rcannood** [comment] 2020-10-12 13:54
Oops, sorry! I forgot to update the namespace file in my latest PR. I'll have it fixed soon.

**Comment by rcannood** [comment] 2020-10-12 13:59
@Helena-todd has merged #4. Could you try again?

**Comment by aoumess** [comment] 2020-10-12 14:48
Thanks to both of you, the install succeeded ;) !

**Comment by GY-amiracle** [comment] 2021-03-13 17:32
Hi!

When I want to install it with `devtools::install_github()` I have the following problem:

```
> devtools::install_github("Helena-todd/TInGa/package")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo Helena-todd/TInGa@HEAD
Skipping 1 packages not available: gng
✓  checking for file ‘/private/var/folders/4k/62f63b357dx_fp7t7yp63_nc0000gn/T/RtmpC6srlz/remotes61bc230a73c7/Helena-todd-TInGa-3d1f041/package/DESCRIPTION’ ...
─  preparing ‘TInGa’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘TInGa_0.0.0.9000.tar.gz’
   
ERROR: dependency ‘gng’ is not available for package ‘TInGa’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TInGa’
Error: Failed to install 'TInGa' from GitHub:
  (converted from warning) installation of package ‘/var/folders/4k/62f63b357dx_fp7t7yp63_nc0000gn/T//RtmpC6srlz/file61bc3760f6c7/TInGa_0.0.0.9000.tar.gz’ had non-zero exit status
```

Best Regards.

**Comment by ZCMei** [comment] 2021-03-21 10:49
> Hi!
> 
> When I want to install it with `devtools::install_github()` I have the following problem:
> 
> ```
> > devtools::install_github("Helena-todd/TInGa/package")
> Using github PAT from envvar GITHUB_PAT
> Downloading GitHub repo Helena-todd/TInGa@HEAD
> Skipping 1 packages not available: gng
> ✓  checking for file ‘/private/var/folders/4k/62f63b357dx_fp7t7yp63_nc0000gn/T/RtmpC6srlz/remotes61bc230a73c7/Helena-todd-TInGa-3d1f041/package/DESCRIPTION’ ...
> ─  preparing ‘TInGa’:
> ✓  checking DESCRIPTION meta-information ...
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘TInGa_0.0.0.9000.tar.gz’
>    
> ERROR: dependency ‘gng’ is not available for package ‘TInGa’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TInGa’
> Error: Failed to install 'TInGa' from GitHub:
>   (converted from warning) installation of package ‘/var/folders/4k/62f63b357dx_fp7t7yp63_nc0000gn/T//RtmpC6srlz/file61bc3760f6c7/TInGa_0.0.0.9000.tar.gz’ had non-zero exit status
> ```
> 
> Best Regards.

I also had the same problem, which was solved after I installed gng from https://github.com/rcannood/gng

**Comment by Helena-todd** [comment] 2021-03-22 07:49
Hi!

Indeed, the 'gng' dependency issue should be solved by installing the gng package from here https://github.com/rcannood/gng as ZCMei suggested.

GY-amiracle, installing the gng package, restarting R, and relaunching the installation of TInGa using devtools should work. Please let me know if you'd run into further issues. 

Best regards,
Helena

**Comment by GY-amiracle** [comment] 2021-03-22 08:16
Thank you very much! The problem is solved.

**Comment by Helena-todd** [comment] 2021-03-22 13:05
Great! I'm glad it's solved

**Closed as completed** 2021-03-22 13:05 UTC
